<a href="https://colab.research.google.com/github/sonjoy1s/Rnn_DeepLearning/blob/main/RNN_module3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [117]:
import pandas as pd

In [118]:
df = pd.read_csv("/content/gk_qna_dataset.csv")
df.head()

                            question  answer
0   What is the capital of "France"?   Paris
1  What is the capital of "Germany"?  Berlin
2    What is the capital of "Italy"?    Rome
3    What is the capital of "Spain"?  Madrid
4    What is the capital of "Japan"?   Tokyo

In [119]:
df['question'][1]

'What is the capital of "Germany"?'

**Tokenize**

In [120]:
import re
def tokenize(text):
  #Lowercase
  text = text.lower()


  #romoved quotes
  text = re.sub(r"[\"']","",text)
  text = re.sub(r"[‘’]","",text)

  #removed all punctuation
  text = re.sub(r"[^\w\s]","",text)
  punctuations = re.sub(r"[^a-z0-9\s]"," ",text)

  #removed extra space
  text = text.replace("\n", " ")


  #tokenize split into words
  tokens = text.split()

  return tokens

In [121]:
print(tokenize(df['question'][9]))

['what', 'is', 'the', 'capital', 'of', 'china']

vocab formating

In [122]:
vocab ={'<UNK>':0}

In [123]:
vocab

{'<UNK>': 0}

In [124]:
def build_vocab(row):
 # print(row['question'],row['answer'])
  tokenize_question = tokenize(row['question'])
  tokenize_answer = tokenize(row['answer'])


  #print(tokenize_question)
  #print(tokenize_answer)

  # merge tokenize
  merge_tokens = tokenize_question + tokenize_answer

  #print(merge_tokens)

  for token in merge_tokens:
    if token not in vocab:
      vocab[token] = len(vocab)

In [125]:
df.apply(build_vocab,axis=1)

0      None
1      None
2      None
3      None
4      None
       ...
166    None
167    None
168    None
169    None
170    None
Length: 171, dtype: object

In [126]:
vocab

{'<UNK>': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france': 6,
 'paris': 7,
 'germany': 8,
 'berlin': 9,
 'italy': 10,
 'rome': 11,
 'spain': 12,
 'madrid': 13,
 'japan': 14,
 'tokyo': 15,
 'canada': 16,
 'ottawa': 17,
 'brazil': 18,
 'brasilia': 19,
 'australia': 20,
 'canberra': 21,
 'india': 22,
 'new': 23,
 'delhi': 24,
 'china': 25,
 'beijing': 26,
 'russia': 27,
 'moscow': 28,
 'united': 29,
 'states': 30,
 'washington': 31,
 'dc': 32,
 'mexico': 33,
 'city': 34,
 'egypt': 35,
 'cairo': 36,
 'turkey': 37,
 'ankara': 38,
 'argentina': 39,
 'buenos': 40,
 'aires': 41,
 'south': 42,
 'korea': 43,
 'seoul': 44,
 'indonesia': 45,
 'jakarta': 46,
 'pakistan': 47,
 'islamabad': 48,
 'bangladesh': 49,
 'dhaka': 50,
 'nepal': 51,
 'kathmandu': 52,
 'sri': 53,
 'lanka': 54,
 'colombo': 55,
 'thailand': 56,
 'bangkok': 57,
 'malaysia': 58,
 'kuala': 59,
 'lumpur': 60,
 'vietnam': 61,
 'hanoi': 62,
 'uae': 63,
 'abu': 64,
 'dhabi': 65,
 'iran': 66,
 'tehran': 67,
 'iraq': 68,
 'baghdad': 69,
 'saudi': 70,
 'arabia': 71,
 'riyadh': 72,
 'nigeria': 73,
 'abuja': 74,
 'kenya': 75,
 'nairobi': 76,
 'chile': 77,
 'santiago': 78,
 'who': 79,
 'discovered': 80,
 'gravity': 81,
 'isaac': 82,
 'newton': 83,
 'invented': 84,
 'telephone': 85,
 'alexander': 86,
 'graham': 87,
 'bell': 88,
 'h2o': 89,
 'commonly': 90,
 'called': 91,
 'water': 92,
 'which': 93,
 'gas': 94,
 'do': 95,
 'plants': 96,
 'absorb': 97,
 'carbon': 98,
 'dioxide': 99,
 'planet': 100,
 'known': 101,
 'as': 102,
 'red': 103,
 'mars': 104,
 'painted': 105,
 'mona': 106,
 'lisa': 107,
 'leonardo': 108,
 'da': 109,
 'vinci': 110,
 'largest': 111,
 'ocean': 112,
 'pacific': 113,
 'developed': 114,
 'theory': 115,
 'relativity': 116,
 'albert': 117,
 'einstein': 118,
 'ai': 119,
 'short': 120,
 'for': 121,
 'artificial': 122,
 'intelligence': 123,
 'ml': 124,
 'machine': 125,
 'learning': 126,
 'nlp': 127,
 'natural': 128,
 'language': 129,
 'processing': 130,
 'does': 131,
 'cpu': 132,
 'stand': 133,
 'central': 134,
 'unit': 135,
 'ram': 136,
 'computer': 137,
 'memory': 138,
 'gpu': 139,
 'graphics': 140,
 'a': 141,
 'url': 142,
 'web': 143,
 'address': 144,
 'http': 145,
 'hypertext': 146,
 'transfer': 147,
 'protocol': 148,
 'json': 149,
 'used': 150,
 'data': 151,
 'exchange': 152,
 'sql': 153,
 'database': 154,
 'query': 155,
 'api': 156,
 'mean': 157,
 'application': 158,
 'programming': 159,
 'interface': 160,
 'light': 161,
 'bulb': 162,
 'thomas': 163,
 'edison': 164,
 'airplane': 165,
 'wright': 166,
 'brothers': 167,
 'penicillin': 168,
 'fleming': 169,
 'wrote': 170,
 'hamlet': 171,
 'william': 172,
 'shakespeare': 173,
 'harry': 174,
 'potter': 175,
 'j': 176,
 'k': 177,
 'rowling': 178,
 'country': 179,
 'land': 180,
 'rising': 181,
 'sun': 182,
 'animal': 183,
 'king': 184,
 'jungle': 185,
 'lion': 186,
 'on': 187,
 'earth': 188,
 'blue': 189,
 'whale': 190,
 'bird': 191,
 'cannot': 192,
 'fly': 193,
 'ostrich': 194,
 'loyalty': 195,
 'dog': 196,
 'fruit': 197,
 'typically': 198,
 'apple': 199,
 'yellow': 200,
 'banana': 201,
 'organ': 202,
 'pumps': 203,
 'blood': 204,
 'heart': 205,
 'humans': 206,
 'breathe': 207,
 'oxygen': 208,
 'metal': 209,
 'liquid': 210,
 'at': 211,
 'room': 212,
 'temperature': 213,
 'mercury': 214,
 'instrument': 215,
 'measures': 216,
 'thermometer': 217,
 'pressure': 218,
 'barometer': 219,
 'main': 220,
 'portuguese': 221,
 'spanish': 222,
 'religion': 223,
 'in': 224,
 'islam': 225,
 'national': 226,
 'royal': 227,
 'bengal': 228,
 'tiger': 229,
 'quick': 230,
 'question': 231,
 'you': 232,
 'know': 233,
 'i': 234,
 'was': 235,
 'wondering': 236,
 'hey': 237,
 'about': 238,
 'this': 239,
 'can': 240,
 'tell': 241,
 'me': 242}

**text** **to** **indices**

In [127]:
def text_to_indices(text,vocab):
  indexed_text = []

  for token in tokenize(text):
    #print(token)
    if token in vocab:
      indexed_text.append(vocab[token])
    else:
      indexed_text.append(vocab['<UNK>'])

  return indexed_text

In [128]:
text_to_indices("what is Phitron",vocab)

[1, 2, 0]

# Dataset and dataloader

In [129]:
import torch
from torch.utils.data import Dataset,DataLoader

In [130]:
df.shape[0]

171

In [131]:
index = 0
text_to_indices(df.iloc[index]['question'],vocab)

[1, 2, 3, 4, 5, 6]

In [132]:
class QADataset(Dataset):
  def __init__(self,df,vocab):

    self.df = df
    self.vocab = vocab

  def __len__(self):
    return self.df.shape[0]

  def __getitem__(self,idx):
    numerical_question = text_to_indices(self.df.iloc[index]['question'],vocab)
    numerical_answer = text_to_indices(self.df.iloc[index]['answer'],vocab)


    return torch.tensor(numerical_question),torch.tensor(numerical_answer)

In [133]:
dataset = QADataset(df,vocab)

In [134]:
dataset[1]

(tensor([1, 2, 3, 4, 5, 6]), tensor([7]))

# DataLoader

In [135]:
dataloader = DataLoader(dataset,batch_size=1,shuffle=True)

In [136]:
for question,answer in dataloader:
  print(question)
  print(answer)

tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])

# RNN Architecture

In [137]:
import torch.nn as nn

class simpleRNN(nn.Module):
  def __init__(self, vocab_size, embedding_dim = 50 , hidden_size=64):
    super(simpleRNN, self).__init__()

    self.embedding = nn.Embedding(vocab_size, embedding_dim)
    self.rnn = nn.RNN(embedding_dim, hidden_size, batch_first=True)
    self.fc = nn.Linear(hidden_size, vocab_size)

# forward
  def forward(self, x):
    x = self.embedding(x) # x: (batch_size, seq_len, embedding_dim)
    _, final = self.rnn(x) # final: (num_layers * num_directions, batch_size, hidden_size)

    # Squeeze the first dimension of 'final' to get (batch_size, hidden_size)
    final_hidden_state = final.squeeze(0)

    # Pass the final hidden state to the linear layer
    x = self.fc(final_hidden_state) # x: (batch_size, vocab_size)
    return x

In [138]:
model = simpleRNN(len(vocab))

In [139]:
model

simpleRNN(
  (embedding): Embedding(243, 50)
  (rnn): RNN(50, 64, batch_first=True)
  (fc): Linear(in_features=64, out_features=243, bias=True)
)

In [140]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
epochs = 50

In [141]:
for epoch in range(epochs):
  total_loss = 0
  for question,answer in dataloader:
    optimizer.zero_grad()
    output = model(question)

    target = answer[0][0].unsqueeze(0)

    loss = criterion(output, target)
    loss.backward()
    optimizer.step()
    total_loss += loss.item()

  if (epoch+1)%10 ==0:
    print(f"Epoch{epoch+1:3d}/{epoch} | Loss : {total_loss : .4f}")

Epoch 10/9 | Loss :  0.0683
Epoch 20/19 | Loss :  0.0164
Epoch 30/29 | Loss :  0.0058
Epoch 40/39 | Loss :  0.0023
Epoch 50/49 | Loss :  0.0008

# Prediction

In [142]:
idx_to_word = {index: word for word, index in vocab.items()}

In [143]:
idx_to_word

{0: '<UNK>',
 1: 'what',
 2: 'is',
 3: 'the',
 4: 'capital',
 5: 'of',
 6: 'france',
 7: 'paris',
 8: 'germany',
 9: 'berlin',
 10: 'italy',
 11: 'rome',
 12: 'spain',
 13: 'madrid',
 14: 'japan',
 15: 'tokyo',
 16: 'canada',
 17: 'ottawa',
 18: 'brazil',
 19: 'brasilia',
 20: 'australia',
 21: 'canberra',
 22: 'india',
 23: 'new',
 24: 'delhi',
 25: 'china',
 26: 'beijing',
 27: 'russia',
 28: 'moscow',
 29: 'united',
 30: 'states',
 31: 'washington',
 32: 'dc',
 33: 'mexico',
 34: 'city',
 35: 'egypt',
 36: 'cairo',
 37: 'turkey',
 38: 'ankara',
 39: 'argentina',
 40: 'buenos',
 41: 'aires',
 42: 'south',
 43: 'korea',
 44: 'seoul',
 45: 'indonesia',
 46: 'jakarta',
 47: 'pakistan',
 48: 'islamabad',
 49: 'bangladesh',
 50: 'dhaka',
 51: 'nepal',
 52: 'kathmandu',
 53: 'sri',
 54: 'lanka',
 55: 'colombo',
 56: 'thailand',
 57: 'bangkok',
 58: 'malaysia',
 59: 'kuala',
 60: 'lumpur',
 61: 'vietnam',
 62: 'hanoi',
 63: 'uae',
 64: 'abu',
 65: 'dhabi',
 66: 'iran',
 67: 'tehran',
 68: 'iraq',
 69: 'baghdad',
 70: 'saudi',
 71: 'arabia',
 72: 'riyadh',
 73: 'nigeria',
 74: 'abuja',
 75: 'kenya',
 76: 'nairobi',
 77: 'chile',
 78: 'santiago',
 79: 'who',
 80: 'discovered',
 81: 'gravity',
 82: 'isaac',
 83: 'newton',
 84: 'invented',
 85: 'telephone',
 86: 'alexander',
 87: 'graham',
 88: 'bell',
 89: 'h2o',
 90: 'commonly',
 91: 'called',
 92: 'water',
 93: 'which',
 94: 'gas',
 95: 'do',
 96: 'plants',
 97: 'absorb',
 98: 'carbon',
 99: 'dioxide',
 100: 'planet',
 101: 'known',
 102: 'as',
 103: 'red',
 104: 'mars',
 105: 'painted',
 106: 'mona',
 107: 'lisa',
 108: 'leonardo',
 109: 'da',
 110: 'vinci',
 111: 'largest',
 112: 'ocean',
 113: 'pacific',
 114: 'developed',
 115: 'theory',
 116: 'relativity',
 117: 'albert',
 118: 'einstein',
 119: 'ai',
 120: 'short',
 121: 'for',
 122: 'artificial',
 123: 'intelligence',
 124: 'ml',
 125: 'machine',
 126: 'learning',
 127: 'nlp',
 128: 'natural',
 129: 'language',
 130: 'processing',
 131: 'does',
 132: 'cpu',
 133: 'stand',
 134: 'central',
 135: 'unit',
 136: 'ram',
 137: 'computer',
 138: 'memory',
 139: 'gpu',
 140: 'graphics',
 141: 'a',
 142: 'url',
 143: 'web',
 144: 'address',
 145: 'http',
 146: 'hypertext',
 147: 'transfer',
 148: 'protocol',
 149: 'json',
 150: 'used',
 151: 'data',
 152: 'exchange',
 153: 'sql',
 154: 'database',
 155: 'query',
 156: 'api',
 157: 'mean',
 158: 'application',
 159: 'programming',
 160: 'interface',
 161: 'light',
 162: 'bulb',
 163: 'thomas',
 164: 'edison',
 165: 'airplane',
 166: 'wright',
 167: 'brothers',
 168: 'penicillin',
 169: 'fleming',
 170: 'wrote',
 171: 'hamlet',
 172: 'william',
 173: 'shakespeare',
 174: 'harry',
 175: 'potter',
 176: 'j',
 177: 'k',
 178: 'rowling',
 179: 'country',
 180: 'land',
 181: 'rising',
 182: 'sun',
 183: 'animal',
 184: 'king',
 185: 'jungle',
 186: 'lion',
 187: 'on',
 188: 'earth',
 189: 'blue',
 190: 'whale',
 191: 'bird',
 192: 'cannot',
 193: 'fly',
 194: 'ostrich',
 195: 'loyalty',
 196: 'dog',
 197: 'fruit',
 198: 'typically',
 199: 'apple',
 200: 'yellow',
 201: 'banana',
 202: 'organ',
 203: 'pumps',
 204: 'blood',
 205: 'heart',
 206: 'humans',
 207: 'breathe',
 208: 'oxygen',
 209: 'metal',
 210: 'liquid',
 211: 'at',
 212: 'room',
 213: 'temperature',
 214: 'mercury',
 215: 'instrument',
 216: 'measures',
 217: 'thermometer',
 218: 'pressure',
 219: 'barometer',
 220: 'main',
 221: 'portuguese',
 222: 'spanish',
 223: 'religion',
 224: 'in',
 225: 'islam',
 226: 'national',
 227: 'royal',
 228: 'bengal',
 229: 'tiger',
 230: 'quick',
 231: 'question',
 232: 'you',
 233: 'know',
 234: 'i',
 235: 'was',
 236: 'wondering',
 237: 'hey',
 238: 'about',
 239: 'this',
 240: 'can',
 241: 'tell',
 242: 'me'}

In [115]:
def prediction(model, question, idx_to_word):
  model.eval()
  with torch.no_grad():
    indices = text_to_indices(question, vocab)
    if not indices:
      return "<UNK>"

    x = torch.tensor(indices).unsqueeze(0)

    pred = torch.argmax(model(x), dim=1).item()

    return idx_to_word[pred]

In [145]:
#TEST
tests = [
    "what is the capital of France?",
    "How is H2O Commonly called?",
]
for q in tests:
  print(f"{q:45} -> {prediction(model, q, idx_to_word)}")

what is the capital of France?                -> paris
How is H2O Commonly called?                   -> da