<a href="https://colab.research.google.com/github/sonjoy1s/Rnn_DeepLearning/blob/main/RNN_module3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import pandas as pd

In [22]:
df = pd.read_csv("/content/gk_qna_dataset.csv")
df.head()

                            question  answer
0   What is the capital of "France"?   Paris
1  What is the capital of "Germany"?  Berlin
2    What is the capital of "Italy"?    Rome
3    What is the capital of "Spain"?  Madrid
4    What is the capital of "Japan"?   Tokyo

In [23]:
df['question'][1]

'What is the capital of "Germany"?'

**Tokenize**

In [24]:
import re
def tokenize(text):
  #Lowercase
  text = text.lower()


  #romoved quotes
  text = re.sub(r"[\"']","",text)
  text = re.sub(r"[‘’]","",text)

  #removed all punctuation
  text = re.sub(r"[^\w\s]","",text)
  punctuations = re.sub(r"[^a-z0-9\s]"," ",text)

  #removed extra space
  text = text.replace("\n", " ")


  #tokenize split into words
  tokens = text.split()

  return tokens

In [25]:
print(tokenize(df['question'][9]))

['what', 'is', 'the', 'capital', 'of', 'china']

vocab formating

In [26]:
vocab ={'<UNK>':0}

In [27]:
vocab

{'<UNK>': 0}

In [39]:
def build_vocab(row):
 # print(row['question'],row['answer'])
  tokenize_question = tokenize(row['question'])
  tokenize_answer = tokenize(row['answer'])


  #print(tokenize_question)
  #print(tokenize_answer)

  # merge tokenize
  merge_tokens = tokenize_question + tokenize_answer

  #print(merge_tokens)

  for token in merge_tokens:
    if token not in vocab:
      vocab[token] = len(vocab)

In [40]:
df.apply(build_vocab,axis=1)

0      None
1      None
2      None
3      None
4      None
       ...
166    None
167    None
168    None
169    None
170    None
Length: 171, dtype: object

In [41]:
vocab

{'<UNK>': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france': 6,
 'paris': 7,
 'germany': 8,
 'berlin': 9,
 'italy': 10,
 'rome': 11,
 'spain': 12,
 'madrid': 13,
 'japan': 14,
 'tokyo': 15,
 'canada': 16,
 'ottawa': 17,
 'brazil': 18,
 'brasilia': 19,
 'australia': 20,
 'canberra': 21,
 'india': 22,
 'new': 23,
 'delhi': 24,
 'china': 25,
 'beijing': 26,
 'russia': 27,
 'moscow': 28,
 'united': 29,
 'states': 30,
 'washington': 31,
 'dc': 32,
 'mexico': 33,
 'city': 34,
 'egypt': 35,
 'cairo': 36,
 'turkey': 37,
 'ankara': 38,
 'argentina': 39,
 'buenos': 40,
 'aires': 41,
 'south': 42,
 'korea': 43,
 'seoul': 44,
 'indonesia': 45,
 'jakarta': 46,
 'pakistan': 47,
 'islamabad': 48,
 'bangladesh': 49,
 'dhaka': 50,
 'nepal': 51,
 'kathmandu': 52,
 'sri': 53,
 'lanka': 54,
 'colombo': 55,
 'thailand': 56,
 'bangkok': 57,
 'malaysia': 58,
 'kuala': 59,
 'lumpur': 60,
 'vietnam': 61,
 'hanoi': 62,
 'uae': 63,
 'abu': 64,
 'dhabi': 65,
 'iran': 66,
 'tehran': 67,
 'iraq': 68,
 'baghdad': 69,
 'saudi': 70,
 'arabia': 71,
 'riyadh': 72,
 'nigeria': 73,
 'abuja': 74,
 'kenya': 75,
 'nairobi': 76,
 'chile': 77,
 'santiago': 78,
 'who': 79,
 'discovered': 80,
 'gravity': 81,
 'isaac': 82,
 'newton': 83,
 'invented': 84,
 'telephone': 85,
 'alexander': 86,
 'graham': 87,
 'bell': 88,
 'h2o': 89,
 'commonly': 90,
 'called': 91,
 'water': 92,
 'which': 93,
 'gas': 94,
 'do': 95,
 'plants': 96,
 'absorb': 97,
 'carbon': 98,
 'dioxide': 99,
 'planet': 100,
 'known': 101,
 'as': 102,
 'red': 103,
 'mars': 104,
 'painted': 105,
 'mona': 106,
 'lisa': 107,
 'leonardo': 108,
 'da': 109,
 'vinci': 110,
 'largest': 111,
 'ocean': 112,
 'pacific': 113,
 'developed': 114,
 'theory': 115,
 'relativity': 116,
 'albert': 117,
 'einstein': 118,
 'ai': 119,
 'short': 120,
 'for': 121,
 'artificial': 122,
 'intelligence': 123,
 'ml': 124,
 'machine': 125,
 'learning': 126,
 'nlp': 127,
 'natural': 128,
 'language': 129,
 'processing': 130,
 'does': 131,
 'cpu': 132,
 'stand': 133,
 'central': 134,
 'unit': 135,
 'ram': 136,
 'computer': 137,
 'memory': 138,
 'gpu': 139,
 'graphics': 140,
 'a': 141,
 'url': 142,
 'web': 143,
 'address': 144,
 'http': 145,
 'hypertext': 146,
 'transfer': 147,
 'protocol': 148,
 'json': 149,
 'used': 150,
 'data': 151,
 'exchange': 152,
 'sql': 153,
 'database': 154,
 'query': 155,
 'api': 156,
 'mean': 157,
 'application': 158,
 'programming': 159,
 'interface': 160,
 'light': 161,
 'bulb': 162,
 'thomas': 163,
 'edison': 164,
 'airplane': 165,
 'wright': 166,
 'brothers': 167,
 'penicillin': 168,
 'fleming': 169,
 'wrote': 170,
 'hamlet': 171,
 'william': 172,
 'shakespeare': 173,
 'harry': 174,
 'potter': 175,
 'j': 176,
 'k': 177,
 'rowling': 178,
 'country': 179,
 'land': 180,
 'rising': 181,
 'sun': 182,
 'animal': 183,
 'king': 184,
 'jungle': 185,
 'lion': 186,
 'on': 187,
 'earth': 188,
 'blue': 189,
 'whale': 190,
 'bird': 191,
 'cannot': 192,
 'fly': 193,
 'ostrich': 194,
 'loyalty': 195,
 'dog': 196,
 'fruit': 197,
 'typically': 198,
 'apple': 199,
 'yellow': 200,
 'banana': 201,
 'organ': 202,
 'pumps': 203,
 'blood': 204,
 'heart': 205,
 'humans': 206,
 'breathe': 207,
 'oxygen': 208,
 'metal': 209,
 'liquid': 210,
 'at': 211,
 'room': 212,
 'temperature': 213,
 'mercury': 214,
 'instrument': 215,
 'measures': 216,
 'thermometer': 217,
 'pressure': 218,
 'barometer': 219,
 'main': 220,
 'portuguese': 221,
 'spanish': 222,
 'religion': 223,
 'in': 224,
 'islam': 225,
 'national': 226,
 'royal': 227,
 'bengal': 228,
 'tiger': 229,
 'quick': 230,
 'question': 231,
 'you': 232,
 'know': 233,
 'i': 234,
 'was': 235,
 'wondering': 236,
 'hey': 237,
 'about': 238,
 'this': 239,
 'can': 240,
 'tell': 241,
 'me': 242}

**text** **to** **indices**

In [44]:
def text_to_indices(text,vocab):
  indexed_text = []

  for token in tokenize(text):
    #print(token)
    if token in vocab:
      indexed_text.append(vocab[token])
    else:
      indexed_text.append(vocab['<UNK>'])

  return indexed_text

In [45]:
text_to_indices("what is Phitron",vocab)

[1, 2, 0]

# Dataset and dataloader

In [47]:
import torch
from torch.utils.data import Dataset,DataLoader

In [48]:
df.shape[0]

171

In [54]:
index = 0
text_to_indices(df.iloc[index]['question'],vocab)

[1, 2, 3, 4, 5, 6]

In [61]:
class QADataset(Dataset):
  def __init__(self,df,vocab):

    self.df = df
    self.vocab = vocab

  def __len__(self):
    return self.df.shape[0]

  def __getitem__(self,idx):
    numerical_question = text_to_indices(self.df.iloc[index]['question'],vocab)
    numerical_answer = text_to_indices(self.df.iloc[index]['answer'],vocab)


    return torch.tensor(numerical_question),torch.tensor(numerical_answer)

In [62]:
dataset = QADataset(df,vocab)

In [63]:
dataset[1]

(tensor([1, 2, 3, 4, 5, 6]), tensor([7]))

# DataLoader

In [64]:
dataloader = DataLoader(dataset,batch_size=1,shuffle=True)

In [65]:
for question,answer in dataloader:
  print(question)
  print(answer)

tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])